# Generated by Django 5.1.2 on 2024-10-24 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0002_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="last_active",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
